server:
  port: 8084

spring:
  application:
    name: MOVIE-SERVICE
  neo4j:
    uri: ${SPRING_NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${SPRING_NEO4J_AUTHENTICATION_USERNAME:neo4j}
      password: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD:password}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
